package ca.damocles.lootsystem;

public enum Items {
	EXCALIBUR, RORAN, BAT, KENDO_SWORD, MURAMASA, PLATINUM_SCIMITAR,
	BRONZE_SWORD, STEEL_SHORT_SWORD, STEEL_LONG_SWORD, STEEL_RAPIER,
	ENDER_RING, SILVER_RING;
}
