package xyz.almia.enchantsystem;

public enum Enchantments {
	
	LIFESTEAL, JUMP, SPEED, SOULSHOT, BAT_VISION, ASSASSIN, VOLLEY, SNARE, WILD_MARK,
	HOLY_SMITE, DEMON_SIPHON, BLOODTHIRST, PETRIFY, EYEPATCH, SWIPE, PROTECTION, SHARPENED, FLAME;
	
}
