name: SevenKings
version: 3.8
author: Kowagatte
main: xyz.almia.cardinalsystem.Cardinal
commands:
  cardinal:
    description: creates detailed items.
  balance:
    description: shows characters bank balance.
  money:
    description: modifies characters bank balance.
  add:
    description: creates detailed items.
  heal:
    description: heal the player.
  rank:
    description: master rank command.
  clan:
    description: clan main command.
  hat:
    description: sets item in hand to helmet
  stats:
    description: player stats.
  help:
    description: command help.
  serialize:
    description: command help.
  logout:
    description: Logs the user out of the character he is currently using.
  rune:
    description: Use command for help options.
    aliases: [runes, enchant, enchants]