name: SevenKings
version: 1.5.0
author: Kowagatte
main: xyz.almia.cardinalsystem.Cardinal
commands:
  cardinal:
    description: creates detailed items.
  balance:
    description: shows characters bank balance.
    aliases: [bal]
  money:
    description: modifies characters bank balance.
  add:
    description: creates detailed items.
  arrow:
    description: master command for arrows.
  heal:
    description: heal the player.
  rank:
    description: master rank command.
  clan:
    description: clan main command.
  stats:
    description: player stats.
  help:
    description: command help.
  logout:
    description: Logs the user out of the character he is currently using.
  rune:
    description: Use command for help options.
    aliases: [runes, enchant, enchants]