name: SevenKings
version: 1.9.0
author: Kowagatte
main: ca.damocles.cardinalsystem.Cardinal
commands:
  cardinal:
    description: shows custom weapon menu.
  spell:
    description: generates spell related items.
  debuging:
    description: should not be used, will be wiped every update. Used to test specific functions during development.
  balance:
    description: shows characters bank balance.
    aliases: [bal]
  money:
    description: modifies characters bank balance.
  party:
    description: master party command.
  trade:
    description: master trade command.
  guild:
    description: master guild command.
  arrow:
    description: master command for arrows.
  potion:
    description: master command for potions.
  heal:
    description: heal the player.
  rank:
    description: master rank command.
  clan:
    description: clan main command.
  stats:
    description: displays a book menu of the player stats.
  help:
    description: command help.
  logout:
    description: Logs the user out of the character he is currently using.
  cast:
    description: Casts spells.
  rune:
    description: Use command for help options.
    aliases: [runes, enchant, enchants]