package xyz.almia.potionsystem;

public enum PotionType {
	HEAL, MANA, SPEED, SLOW,
	HARM, JUMP, NAUSEA, REGEN,
	RESISTANCE, FIRE_RESIST,
	BLIND, HUNGER, WEAKNESS,
	POISON, WITHER, FIRE,
	EXPLOSION, LIGHTNING,
	SOUL, NONE;
}
